var testGeneticSoylent = new GeneticSoylent({
      ingredients: ingredients,
      targetNutrients: {
          'soluble-fiber': {min: 0, max: 0, importanceFactor: 1},
          'saturated-fat': {min: 0, max: 0, importanceFactor: 1},
          'polyunsaturated-fat': {min: 0, max: 0, importanceFactor: 1},
          'monounsaturated-fat': {min: 0, max: 0, importanceFactor: 1},
          'insoluble-fiber': {min: 0, max: 0, importanceFactor: 1},
          'calories': {min:2633, max: 2833, importanceFactor: 1},
          'carbs': {min:0, max: 404, importanceFactor: 1},
          'protein': {min: 0, max: 142, importanceFactor: 1},
          'fat': {min: 0, max: 63, importanceFactor: 1},
          'omega_3': {min: 0, max: 1.6, importanceFactor: 1},
          'omega_6': {min: 0, max: 17, importanceFactor: 1},
          'fiber': {min: 0, max: 28, importanceFactor: 1},
          'cholesterol': {min: 0, max: 0, importanceFactor: 1},
          'calcium': {min: 1, max: 2.5, importanceFactor: 1},
          'chloride': {min: 2.3, max: 3.6, importanceFactor: 1},
          'chromium': {min: 0, max: 35, importanceFactor: 1},
          'copper': {min: 0.9, max: 10, importanceFactor: 1},
          'iodine': {min: 150, max: 110, importanceFactor: 1},
          'iron': {min: 8, max: 45, importanceFactor: 1},
          'magnesium': {min: 0, max: 420, importanceFactor: 1},
          'maganese': {min: 0, max: 420, importanceFactor: 1},
          'molybdenum': {min: 0, max: 420, importanceFactor: 1},
          'phosphorus': {min: 0, max: 420, importanceFactor: 1},
          'potassium': {min: 0, max: 420, importanceFactor: 1},
          'selinium': {min: 0, max: 420, importanceFactor: 1},
          'sodium': {min: 0, max: 420, importanceFactor: 1},
          'sulfur': {min: 0, max: 420, importanceFactor: 1},
          'zinc': {min: 0, max: 420, importanceFactor: 1},
          'vitamin_a': {min: 0, max: 420, importanceFactor: 1},
          'vitamin_b6': {min: 0, max: 420, importanceFactor: 1},
          'vitamin_b12': {min: 0, max: 420, importanceFactor: 1},
          'vitamin_c': {min: 0, max: 420, importanceFactor: 1},
          'vitamin_d': {min: 0, max: 420, importanceFactor: 1},
          'vitamin_e': {min: 0, max: 420, importanceFactor: 1},
          'vitamin_k': {min: 0, max: 420, importanceFactor: 1},
          'thiamin': {min: 0, max: 420, importanceFactor: 1},
          'riboflavin': {min: 0, max: 420, importanceFactor: 1},
          'niacin': {min: 0, max: 420, importanceFactor: 1},
          'folate': {min: 0, max: 420, importanceFactor: 1},
          'panthothenic': {min: 0, max: 420, importanceFactor: 1},
          'biotin': {min: 0, max: 420, importanceFactor: 1},
          'choline': {min: 0, max: 420, importanceFactor: 1},
      }
  });